const { createCanvas } = require('canvas');
const fs = require('fs').promises;
const path = require('path');

class ImageService {
  
  constructor() {
    this.cachePath = path.join(__dirname, '..', 'cache');
    this.imagePath = path.join(this.cachePath, 'summary.png');
  }

  async ensureCacheDirectory() {
    try {
      await fs.mkdir(this.cachePath, { recursive: true });
    } catch (error) {
      console.error('Error creating cache directory:', error);
    }
  }

  async generateSummaryImage(countries) {
    await this.ensureCacheDirectory();

    // Filter and sort countries by GDP
    const top5 = countries
      .filter(c => c.estimated_gdp !== null && c.estimated_gdp > 0)
      .sort((a, b) => parseFloat(b.estimated_gdp) - parseFloat(a.estimated_gdp))
      .slice(0, 5);

    // Create canvas
    const width = 800;
    const height = 600;
    const canvas = createCanvas(width, height);
    const ctx = canvas.getContext('2d');

    // Background gradient
    const gradient = ctx.createLinearGradient(0, 0, 0, height);
    gradient.addColorStop(0, '#1a1a2e');
    gradient.addColorStop(1, '#16213e');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, width, height);

    // Title
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 32px Arial';
    ctx.fillText('Country Summary Report', 50, 60);

    // Total countries
    ctx.font = '24px Arial';
    ctx.fillStyle = '#00d4ff';
    ctx.fillText(`Total Countries: ${countries.length}`, 50, 120);

    // Last refresh timestamp
    ctx.font = '18px Arial';
    ctx.fillStyle = '#aaaaaa';
    const timestamp = new Date().toISOString();
    ctx.fillText(`Last Updated: ${timestamp}`, 50, 155);

    // Top 5 header
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 26px Arial';
    ctx.fillText('Top 5 Countries by Estimated GDP', 50, 210);

    // Draw top 5 countries
    ctx.font = '20px Arial';
    let y = 260;
    
    top5.forEach((country, index) => {
      // Rank number
      ctx.fillStyle = '#00ff88';
      ctx.fillText(`${index + 1}.`, 70, y);
      
      // Country name
      ctx.fillStyle = '#ffffff';
      ctx.fillText(country.name, 110, y);
      
      // GDP value
      ctx.fillStyle = '#ffaa00';
      const gdpValue = parseFloat(country.estimated_gdp);
      const gdp = gdpValue.toLocaleString('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
      });
      ctx.fillText(gdp, 400, y);
      
      y += 50;
    });

    // Footer
    ctx.fillStyle = '#666666';
    ctx.font = '16px Arial';
    ctx.fillText('Generated by Country Currency API', 50, 550);

    // Save image
    const buffer = canvas.toBuffer('image/png');
    await fs.writeFile(this.imagePath, buffer);
    
    console.log('✓ Summary image generated');
  }

  async getImagePath() {
    try {
      await fs.access(this.imagePath);
      return this.imagePath;
    } catch (error) {
      return null;
    }
  }
}

module.exports = new ImageService();